### PR TITLE
New controls and layouts. And more...

### PR DESCRIPTION
**Pull request by sleonidy**
Hi, 
New controls and layouts implemented:

- NotificationsPane
- Custom TextFields
- PropertySheet
- HiddenSlidePane
- Notifications
- WorldMapView
- InfoOverlay
- Borders

Also:
- Moved controls to package tornadofx.controlsfx
- Update kotlin to 1.1.60 
- gradle wrapper to 4.3.1

### CODE REVIEW

**Comment by edvin** [comment]
Wow! Anything else you'd like to include before the first release, or should I push it out now?

**Comment by sleonidy** [comment]
Hi,
Let me update the Readme with Thomas' implementations(Will try to do it
today/tomorrow) and we are ready to release.
Also, do you want to configure gradle for bintray or you are doing release
manually ?

**Comment by thomasnield** [comment]
@sleonidy you are awesome, thank you! We will need to credit you with helping getting this off the ground! @edvin as soon as Leonid feels this is good to go, let's ship a 0.x release!

**Comment by edvin** [comment]
Cool with me. I'll add the relevant bits to the build so we can release to Maven Central automatically :)

**Comment by sleonidy** [comment]
Thanks for kind words. Tomorrow I'll add some more controls and we will be
ready for the release.

**Pull request merged**
