### PR TITLE
New controls,dialogs and layouts

### PR DESCRIPTION
**Pull request by sleonidy**
New controls implemented:
- RangeSlider
- StatusBar
- Rating
- PopOver
- Plus/Minus Slider
- HyperlinkLabel
Layouts:
-  MasterDetailPane
- MaskerPane
Dialogs:
- ProgressDialog
- ExceptionDialog

### CODE REVIEW

**Review by edvin — APPROVED** [review]
Wow :) Fantastic! Thank you so much for this!

**Comment by sleonidy** [comment]
Will be more later ... :) 
Thanks.

**Comment by thomasnield** [comment]
Thank you @sleonidy! This is awesome. 

FYI if you are in the rhythm of implementing builders, I need help with TornadoFX-ControlsFX too. 
https://github.com/edvin/tornadofx-controlsfx

**Comment by thomasnield** [comment]
Thank you @sleonidy! This is awesome : )

**Pull request merged**
